# Generated by Django 6.1.1 on 2026-10-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('manager', models.CharField(max_length=150, verbose_name='Керівник')),
                ('address', models.TextField(verbose_name='Адреса')),
                ('count_workers', models.IntegerField(default=0, verbose_name='Кількість працівників')),
            ],
            options={
                'verbose_name': 'Підрозділ',
                'verbose_name_plural': 'Підрозділи',
                'db_table': 'unit',
            },
        ),
    ]
