# Generated by Django 6.1.1 on 2026-10-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата початку')),
                ('date_end', models.DateField(verbose_name='Дата кінця')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('count_day', models.IntegerField(verbose_name='Кількість днів')),
            ],
            options={
                'verbose_name': 'Документ відсутності',
                'verbose_name_plural': 'Документи відсутності',
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='TypeMissing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип відсутності')),
            ],
            options={
                'verbose_name': 'Тип відсутності',
                'verbose_name_plural': 'Типи відсутності',
                'db_table': 'type_missing',
            },
        ),
    ]
