# Generated by Django 6.1.1 on 2026-10-06 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='worker',
            field=models.ForeignKey(db_column='tabel_num', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workers.worker', to_field='tabel_num'),
        ),
        migrations.AddField(
            model_name='document',
            name='type_missing',
            field=models.ForeignKey(db_column='id_type_missing', on_delete=django.db.models.deletion.CASCADE, to='documents.typemissing', verbose_name='Причина'),
        ),
    ]
