# Generated by Django 6.1.1 on 2026-10-06 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_passport', models.CharField(max_length=100, verbose_name='Номер паспорта')),
                ('tabel_num', models.CharField(max_length=20, unique=True, verbose_name='Табельний номер')),
                ('surname', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('firstname', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('lastname', models.CharField(max_length=50, verbose_name='По батькові')),
                ('phone_num', models.CharField(max_length=13, verbose_name='Номер телефону')),
                ('post', models.CharField(max_length=50, verbose_name='Посада')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('date_joined', models.DateField(verbose_name='Дата прийому на роботу')),
                ('unit', models.ForeignKey(db_column='id_unit_w', on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='unit.unit', verbose_name='Підрозділ')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Працівник',
                'verbose_name_plural': 'Працівники',
                'db_table': 'worker',
            },
        ),
    ]
