# Generated by Django 6.1.1 on 2026-10-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sick_limit',
            field=models.IntegerField(default=10, verbose_name='Ліміт лікарняних (днів)'),
        ),
        migrations.AddField(
            model_name='user',
            name='vacation_limit',
            field=models.IntegerField(default=24, verbose_name='Ліміт відпустки (днів)'),
        ),
    ]
