# Generated by Django 6.1.1 on 2026-10-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.IntegerField(default=0, verbose_name='Відрядження (дні)')),
                ('vacation', models.IntegerField(default=0, verbose_name='Відпустка (дні)')),
                ('hospital', models.IntegerField(default=0, verbose_name='Лікарняний (дні)')),
                ('skip_days', models.IntegerField(default=0, verbose_name='Пропуски (дні)')),
                ('count_work_day', models.IntegerField(default=0, verbose_name='Робочі дні')),
            ],
            options={
                'verbose_name': 'Запис табеля',
                'verbose_name_plural': 'Записи табеля',
                'db_table': 'content_tabel',
            },
        ),
        migrations.CreateModel(
            name='Tabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_month', models.SmallIntegerField(verbose_name='Місяць')),
                ('t_year', models.SmallIntegerField(verbose_name='Рік')),
            ],
            options={
                'verbose_name': 'Табель',
                'verbose_name_plural': 'Табелі',
                'db_table': 'tabel',
            },
        ),
    ]
