# Generated by Django 6.1.1 on 2026-10-06 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timesheets', '0001_initial'),
        ('unit', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttabel',
            name='worker',
            field=models.ForeignKey(db_column='id_worker', on_delete=django.db.models.deletion.CASCADE, related_name='tabel_records', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='tabel',
            name='unit',
            field=models.ForeignKey(db_column='id_unit', on_delete=django.db.models.deletion.CASCADE, related_name='tabels', to='unit.unit', verbose_name='Підрозділ'),
        ),
        migrations.AddField(
            model_name='contenttabel',
            name='tabel',
            field=models.ForeignKey(db_column='id_tabel', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='timesheets.tabel'),
        ),
    ]
